ALTER TABLE `account_log` ADD INDEX `account_id_1` (`account_id`);
ALTER TABLE `account_log` ADD INDEX `tx_new_1` (`tx_new`);
ALTER TABLE `account_log` ADD INDEX `tx_prev_1` (`tx_prev`);
ALTER TABLE `account_name` ADD INDEX `account_id_1` (`account`);
ALTER TABLE `account_name` ADD UNIQUE `name_1` (`name`);
ALTER TABLE `account_name` DROP FOREIGN KEY `account_name-id`;
ALTER TABLE `account_transaction_type` ADD UNIQUE `name_1` (`name`);
ALTER TABLE `account_transaction_type` DROP FOREIGN KEY `account_transaction_type-id`;
ALTER TABLE `account_transaction` ADD INDEX `acct_dst_1` (`acct_dst`);
ALTER TABLE `account_transaction` ADD INDEX `acct_src_1` (`acct_src`);
ALTER TABLE `account_transaction` ADD INDEX `entity_1` (`entity`);
ALTER TABLE `account_transaction` ADD INDEX `ts_1` (`ts`);
ALTER TABLE `account_transaction` ADD INDEX `tx_type_1` (`tx_type`);
ALTER TABLE `account_transaction` ADD INDEX `user_1` (`user_id`);
ALTER TABLE `account_transaction` DROP FOREIGN KEY `account_transaction-id`;
ALTER TABLE `account` ADD INDEX `last_tx_1` (`last_tx`);
ALTER TABLE `account` ADD INDEX `user_1` (`user_id`);
ALTER TABLE `account` DROP FOREIGN KEY `account-id`;
ALTER TABLE `note_session` ADD INDEX `ts_created_1` (`ts_created`);
ALTER TABLE `note_session` ADD INDEX `ts_expires_1` (`ts_expires`);
ALTER TABLE `note_session` ADD UNIQUE `skey_1` (`skey`);
ALTER TABLE `payment_attempt` ADD INDEX `account_1` (`account`);
ALTER TABLE `payment_attempt` ADD INDEX `card_id_1` (`card_id`);
ALTER TABLE `payment_attempt` ADD INDEX `error_id_1` (`error`);
ALTER TABLE `payment_attempt` ADD INDEX `payment_id` (`payment`);
ALTER TABLE `payment_attempt` ADD INDEX `proc_id_1` (`proc_id`);
ALTER TABLE `payment_attempt` ADD INDEX `user_1` (`user_id`);
ALTER TABLE `payment_attempt` DROP FOREIGN KEY `payment_attempt-id`;
ALTER TABLE `payment_card` ADD INDEX `user_1` (`user_id`);
ALTER TABLE `payment_card` DROP FOREIGN KEY `payment_card-id`;
ALTER TABLE `payment_error` DROP FOREIGN KEY `payment_error-id`;
ALTER TABLE `payment_lock` ADD UNIQUE `account_id` (`account`);
ALTER TABLE `payment_lock` DROP FOREIGN KEY `payment_lock-id`;
ALTER TABLE `payment_proc` ADD UNIQUE `name` (`name`);
ALTER TABLE `payment_proc` DROP FOREIGN KEY `payment_proc-id`;
ALTER TABLE `payment` ADD INDEX `account_1` (`account`);
ALTER TABLE `payment` ADD INDEX `card_id_1` (`card_id`);
ALTER TABLE `payment` ADD INDEX `proc_id_1` (`proc_id`);
ALTER TABLE `payment` ADD INDEX `ref_id_1` (`ref_id`);
ALTER TABLE `payment` ADD INDEX `reversed_1` (`reversed`);
ALTER TABLE `payment` ADD INDEX `ts_1` (`ts`);
ALTER TABLE `payment` ADD INDEX `user_1` (`user_id`);
ALTER TABLE `payment` DROP FOREIGN KEY `payment-id`;
ALTER TABLE `ring_button` ADD INDEX `ringpage_id_1` (`ringpage_id`);
ALTER TABLE `ring_button` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_caller` ADD INDEX `cid_number_1` (`cid_number`);
ALTER TABLE `ring_caller` ADD INDEX `did_id_1` (`did_id`);
ALTER TABLE `ring_caller` ADD INDEX `phone_id_1` (`phone_id`);
ALTER TABLE `ring_caller` ADD INDEX `sip_id_1` (`sip_id`);
ALTER TABLE `ring_call_route` ADD INDEX `call_id_1` (`call_id`);
ALTER TABLE `ring_call_route` ADD INDEX `fs_uuid_bleg_1` (`fs_uuid_bleg`);
ALTER TABLE `ring_call` ADD INDEX `caller_user_id_1` (`caller_user_id`, `ts`);
ALTER TABLE `ring_call` ADD INDEX `fs_uuid_aleg_1` (`fs_uuid_aleg`);
ALTER TABLE `ring_call` ADD INDEX `target_user_id_1` (`target_user_id`, `ts`);
ALTER TABLE `ring_cart` ADD INDEX `order_id_1` (`order_id`);
ALTER TABLE `ring_cart` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_cart` ADD UNIQUE `coupon_id_1` (`coupon_id`);
ALTER TABLE `ring_cart` ADD UNIQUE `hashtag_id_1` (`hashtag_id`);
ALTER TABLE `ring_cart` ADD UNIQUE `transaction_id_1` (`transaction_id`);
ALTER TABLE `ring_category` ADD INDEX `category_id_1` (`category_id`);
ALTER TABLE `ring_category` ADD UNIQUE `category` (`category`);
ALTER TABLE `ring_contact_email` ADD INDEX `email_hash_1` (`email_hash`);
ALTER TABLE `ring_contact_email` ADD UNIQUE `contact_id_1` (`contact_id`, `email_hash`);
ALTER TABLE `ring_contact_phone` ADD INDEX `phone_hash_1` (`phone_hash`);
ALTER TABLE `ring_contact_phone` ADD UNIQUE `contact_id_1` (`contact_id`, `phone_hash`);
ALTER TABLE `ring_contact` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_contact` ADD INDEX `user_id_2` (`user_id`, `matched_user_id`);
ALTER TABLE `ring_contact` ADD UNIQUE `device_id_1` (`device_id`, `internal_id`);
ALTER TABLE `ring_conversation` ADD UNIQUE `conversation_code_1` (`conversation_code`);
ALTER TABLE `ring_conversation` ADD UNIQUE `conversation_uuid_1` (`conversation_uuid`);
ALTER TABLE `ring_conversation` ADD UNIQUE `from_user_id_1` (`from_user_id`, `to_user_id`);
ALTER TABLE `ring_coupon` ADD INDEX `transaction_id_1` (`transaction_id`);
ALTER TABLE `ring_coupon` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_coupon` ADD UNIQUE `code_1` (`code`);
ALTER TABLE `ring_coupon` DROP FOREIGN KEY `coupon-transaction_id`;
ALTER TABLE `ring_coupon` DROP FOREIGN KEY `coupon-user_id`;
ALTER TABLE `ring_device` ADD UNIQUE `user_id_1` (`user_id`, `device_uuid`);
ALTER TABLE `ring_did` ADD INDEX `did_hash_1` (`did_hash`);
ALTER TABLE `ring_did` ADD UNIQUE `did_code_1` (`did_code`, `did_number`);
ALTER TABLE `ring_did` DROP FOREIGN KEY `ring_did-id`;
ALTER TABLE `ring_domain_user` ADD UNIQUE `domain_id_1` (`domain_id`, `username`);
ALTER TABLE `ring_domain_user` DROP FOREIGN KEY `ring_domain_user-id`;
ALTER TABLE `ring_domain` ADD INDEX `domain_reverse_2` (`domain_reverse`);
ALTER TABLE `ring_domain` ADD UNIQUE `domain_1` (`domain`);
ALTER TABLE `ring_domain` DROP FOREIGN KEY `ring_domain-id`;
ALTER TABLE `ring_email` ADD INDEX `domain_id_1` (`domain_id`);
ALTER TABLE `ring_email` ADD INDEX `email_hash_1` (`email_hash`);
ALTER TABLE `ring_email` ADD UNIQUE `domain_user_id_1` (`domain_user_id`);
ALTER TABLE `ring_email` ADD UNIQUE `email_1` (`email`);
ALTER TABLE `ring_email` DROP FOREIGN KEY `ring_email-id`;
ALTER TABLE `ring_hashtag_directory` ADD INDEX (`user_id`);
ALTER TABLE `ring_hashtag_directory` ADD UNIQUE `hashtag_id_1` (`hashtag_id`);
ALTER TABLE `ring_hashtag` ADD INDEX `category_id_1` (`category_id`);
ALTER TABLE `ring_hashtag` ADD INDEX `ringpage_id_1` (`ringpage_id`);
ALTER TABLE `ring_hashtag` ADD INDEX `ts_expires_1` (`ts_expires`);
ALTER TABLE `ring_hashtag` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_hashtag` ADD UNIQUE `hashtag_1` (`hashtag`);
ALTER TABLE `ring_monthly_product` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_monthly` ADD INDEX `rebill_date_1` (`rebill_date`);
ALTER TABLE `ring_monthly` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_order` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_order` ADD UNIQUE `transaction_id_1` (`transaction_id`);
ALTER TABLE `ring_page` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_phone` ADD INDEX `gruu_1` (`gruu`);
ALTER TABLE `ring_phone` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_phone` ADD UNIQUE `login_1` (`login`);
ALTER TABLE `ring_phone` DROP FOREIGN KEY `ring_phone-id`;
ALTER TABLE `ring_product` ADD UNIQUE `name_1` (`name`);
ALTER TABLE `ring_route` ADD UNIQUE `user_id_1` (`user_id`, `sip_id`, `did_id`, `phone_id`, `email_id`);
ALTER TABLE `ring_sip` ADD UNIQUE `sip_url_1` (`sip_url`);
ALTER TABLE `ring_target_route` ADD INDEX `route_id_1` (`route_id`);
ALTER TABLE `ring_target_route` ADD UNIQUE `target_id_1` (`target_id`, `seq`);
ALTER TABLE `ring_target` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_target` ADD UNIQUE `did_id_1` (`did_id`);
ALTER TABLE `ring_target` ADD UNIQUE `domain_id_1` (`domain_id`);
ALTER TABLE `ring_target` ADD UNIQUE `email_id_1` (`email_id`);
ALTER TABLE `ring_target` DROP FOREIGN KEY `ring_target-id`;
ALTER TABLE `ring_user_admin` ADD UNIQUE `user_id_1` (`user_id`);
ALTER TABLE `ring_user_apns` ADD UNIQUE `user_id_1` (`user_id`);
ALTER TABLE `ring_user_contact_sync` ADD UNIQUE `user_id_1` (`user_id`, `device_id`);
ALTER TABLE `ring_user_did` ADD INDEX `did_id_1` (`did_id`);
ALTER TABLE `ring_user_did` ADD UNIQUE `user_id_1` (`user_id`, `did_id`);
ALTER TABLE `ring_user_domain` ADD INDEX `domain_id_1` (`domain_id`);
ALTER TABLE `ring_user_domain` ADD UNIQUE `user_id_1` (`user_id`, `domain_id`);
ALTER TABLE `ring_user_domain` DROP FOREIGN KEY `ring_user_domain-id`;
ALTER TABLE `ring_user_email` ADD INDEX `email_id_1` (`email_id`);
ALTER TABLE `ring_user_email` ADD UNIQUE `user_id_1` (`user_id`, `email_id`);
ALTER TABLE `ring_user_email` DROP FOREIGN KEY `ring_user_email-id`;
ALTER TABLE `ring_user_pwreset` ADD UNIQUE `reset_hash_1` (`reset_hash`);
ALTER TABLE `ring_user_pwreset` ADD UNIQUE `user_id_1` (`user_id`);
ALTER TABLE `ring_user_service` ADD UNIQUE `user_id_1` (`user_id`, `service_id`);
ALTER TABLE `ring_user` ADD UNIQUE `aws_user_id_1` (`aws_user_id`);
ALTER TABLE `ring_user` ADD UNIQUE `login_1` (`login`);
ALTER TABLE `ring_user` DROP FOREIGN KEY `ring_user-id`;
ALTER TABLE `ring_verify_did` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_verify_did` ADD UNIQUE `did_id_1` (`did_id`);
ALTER TABLE `ring_verify_domain` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_verify_domain` ADD UNIQUE `domain_id_1` (`domain_id`);
ALTER TABLE `ring_verify_domain` DROP FOREIGN KEY `ring_verify_domain-id`;
ALTER TABLE `ring_verify_email` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_verify_email` ADD UNIQUE `email_id_1` (`email_id`);
ALTER TABLE `ring_verify_email` DROP FOREIGN KEY `ring_verify_email-id`;

INSERT INTO sys_version SET id=23;
