DELIMITER // 
-- CREATE DEFINER=`root`@`localhost` TRIGGER `ringmail`.`ring_hashtag_directory` AFTER DELETE ON `ringmail`.`ring_hashtag_directory` FOR EACH ROW 
CREATE TRIGGER `ringmail`.`ring_hashtag_directory` AFTER DELETE ON `ringmail`.`ring_hashtag_directory` FOR EACH ROW 
begin
	update ring_hashtag set directory = 0 where id = old.hashtag_id;
end
// 
DELIMITER ; 
ALTER TABLE `account_log` ADD INDEX `account_id_1` (`account_id`);
ALTER TABLE `account_name` DROP FOREIGN KEY `account_name-id`;
ALTER TABLE `account_transaction_type` DROP FOREIGN KEY `account_transaction_type-id`;
ALTER TABLE `account_transaction` DROP FOREIGN KEY `account_transaction-id`;
ALTER TABLE `account` DROP FOREIGN KEY `account-id`;
ALTER TABLE `payment_attempt` ADD INDEX `error_id_1` (`error`);
ALTER TABLE `payment_attempt` DROP FOREIGN KEY `payment_attempt-id`;
ALTER TABLE `payment_card` DROP FOREIGN KEY `payment_card-id`;
ALTER TABLE `payment_error` DROP FOREIGN KEY `payment_error-id`;
ALTER TABLE `payment_lock` DROP FOREIGN KEY `payment_lock-id`;
ALTER TABLE `payment_proc` DROP FOREIGN KEY `payment_proc-id`;
ALTER TABLE `payment` ADD INDEX `proc_id_1` (`proc_id`);
ALTER TABLE `payment` DROP FOREIGN KEY `payment-id`;
ALTER TABLE `ring_button` ADD INDEX `ringpage_id_1` (`ringpage_id`);
ALTER TABLE `ring_button` ADD INDEX `user_id_1` (`user_id`);
ALTER TABLE `ring_cart` ADD INDEX `order_id_1` (`order_id`);
ALTER TABLE `ring_cart` ADD UNIQUE `coupon_id_1` (`coupon_id`);
ALTER TABLE `ring_category` ADD INDEX `category_id_1` (`category_id`);
ALTER TABLE `ring_coupon` DROP FOREIGN KEY `coupon-transaction_id`;
ALTER TABLE `ring_coupon` DROP FOREIGN KEY `coupon-user_id`;
ALTER TABLE `ring_did` DROP FOREIGN KEY `ring_did-id`;
ALTER TABLE `ring_domain_user` DROP FOREIGN KEY `ring_domain_user-id`;
ALTER TABLE `ring_domain` DROP FOREIGN KEY `ring_domain-id`;
ALTER TABLE `ring_email` DROP FOREIGN KEY `ring_email-id`;
ALTER TABLE `ring_hashtag_directory` ADD INDEX (`user_id`);
ALTER TABLE `ring_phone` DROP FOREIGN KEY `ring_phone-id`;
ALTER TABLE `ring_target` DROP FOREIGN KEY `ring_target-id`;
ALTER TABLE `ring_user_domain` ADD INDEX `domain_id_1` (`domain_id`);
ALTER TABLE `ring_user_domain` DROP FOREIGN KEY `ring_user_domain-id`;
ALTER TABLE `ring_user_email` DROP FOREIGN KEY `ring_user_email-id`;
ALTER TABLE `ring_user` DROP FOREIGN KEY `ring_user-id`;
ALTER TABLE `ring_verify_domain` DROP FOREIGN KEY `ring_verify_domain-id`;
ALTER TABLE `ring_verify_email` DROP FOREIGN KEY `ring_verify_email-id`;
ALTER TABLE `ring_hashtag` ADD COLUMN `free` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `account_log` DROP INDEX `account_log-account_id`;
ALTER TABLE `payment` DROP INDEX `payment-proc_id`;
ALTER TABLE `payment_attempt` DROP INDEX `payment_attempt-error_id`;
ALTER TABLE `ring_button` DROP INDEX `button-user_id`;
ALTER TABLE `ring_cart` DROP INDEX `ring_cart-order_id`;
ALTER TABLE `ring_category` DROP INDEX `ring_category-category_id`;
ALTER TABLE `ring_user_domain` DROP INDEX `ring_user_domain-domain_id`;
ALTER TABLE `account_log` CHANGE COLUMN `id` `id` bigint(20) unsigned NOT NULL;
ALTER TABLE `account_transaction` CHANGE COLUMN `amount` `amount` decimal(24, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE `note_sequence` DROP COLUMN `timestamp`;
ALTER TABLE `note_sequence` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `payment` DROP INDEX ref_id_1;
ALTER TABLE `payment` DROP INDEX ref_id_2;
ALTER TABLE `payment` CHANGE COLUMN `amount` `amount` decimal(24, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE `payment` CHANGE COLUMN `ts` `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `payment` ADD INDEX `ref_id_1` (`ref_id`);
ALTER TABLE `ring_button` DROP INDEX `ring_button-ringpage_id`;
ALTER TABLE `ring_button` DROP COLUMN `timestamp`;
ALTER TABLE `ring_button` ADD COLUMN `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ring_cart` DROP INDEX `coupon_1`;
ALTER TABLE `ring_cart` ADD CONSTRAINT `ring_cart-hashtag_id` FOREIGN KEY (`hashtag_id`) REFERENCES `ring_hashtag` (`id`) ON DELETE CASCADE;
ALTER TABLE `ring_category` DROP COLUMN `timestamp`;
ALTER TABLE `ring_category` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ring_coupon` ADD CONSTRAINT `ring_coupon-transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `account_transaction` (`id`);
ALTER TABLE `ring_coupon` ADD CONSTRAINT `ring_coupon-user_id` FOREIGN KEY (`user_id`) REFERENCES `ring_user` (`id`);
ALTER TABLE `ring_hashtag_directory` DROP INDEX user_id_2;
ALTER TABLE `ring_monthly_product` CHANGE COLUMN `monthly_price` `monthly_price` decimal(24, 2) NOT NULL;
ALTER TABLE `ring_order` CHANGE COLUMN `total` `total` decimal(24, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE `ring_page` DROP COLUMN `timestamp`;
ALTER TABLE `ring_page` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ring_user_did` CHANGE COLUMN `did_label` `did_label` varchar(64) NOT NULL DEFAULT '';
ALTER TABLE `ring_user_did` CHANGE COLUMN `did_type` `did_type` varchar(16) NOT NULL DEFAULT '';
ALTER TABLE `ring_verify_did` CHANGE COLUMN `tries` `tries` bigint(20) NULL DEFAULT 0;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `ring_button` ADD CONSTRAINT `ring_button-ringpage_id` FOREIGN KEY (`ringpage_id`) REFERENCES `ring_page` (`id`) ON DELETE CASCADE;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO sys_version SET id=26;
